apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - postgres-statefulset.yaml
  - services.yaml
  - configmap.yaml
  - ingress.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: ai-incident-assistant
  app.kubernetes.io/part-of: incident-management
