apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: argo
data:
  default-artifact-repository: |
    archiveLogs: false
    s3:
      bucket: argo-workflows-artifacts
      endpoint: s3.amazonaws.com
      insecure: false
      accessKeySecret:
        name: argo-artifacts
        key: accesskey
      secretKeySecret:
        name: argo-artifacts
        key: secretkey
